### ISSUE TITLE
Pushing into Github but Stopped counting after 72 problems 

### ISSUE THREAD

**Issue by Chouikhi-abdallah** [LeetSync/LeetSync#184]
Describe the bug :
I setup the extension with giving necessary access and set the repository link  , and also set the repository as public ,it works well until the problem number 72 the counter in no longer updated and sometimes it doesn't push into the repository. 

Expected Behavior : 
Whenever I solved any problem , extension should push my code to my GitHub repo and the counter should be incremented

Screenshots : 
<img width="938" alt="Screenshot 2024-08-26 at 12 08 08" src="https://github.com/user-attachments/assets/6e46f607-1dd8-4c33-864e-f59e2c540667">

Desktop (please complete the following information):

OS: MacOs Monterey 12.7.4
Browser: Google Chrome

**Comment by disturbedlord** [comment]
Hi Please check this Issue for Fix 
https://github.com/LeetSync/LeetSync/issues/182

**Comment by Chouikhi-abdallah** [comment]
Thanks for your support i will check your own version
